package ldcache_test

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/KarpelesLab/ldcache"
)

// TestRoundTrip verifies that write→read→write produces stable binary output.
func TestRoundTrip(t *testing.T) {
	f := ldcache.New()
	f.Entries = ldcache.EntryList{
		{Flags: 0x0303, Key: "libfoo.so.1", Value: "/usr/lib/libfoo.so.1.2.3"},
		{Flags: 0x0303, Key: "libbar.so.2", Value: "/usr/lib/libbar.so.2.0.0"},
		{Flags: 0x0303, Key: "libbaz.so.3", Value: "/usr/lib/libbaz.so.3.1.0"},
		{Flags: 0x0103, Key: "libfoo.so.1", Value: "/usr/lib32/libfoo.so.1.2.3"}, // same key, different flags
	}
	sort.Sort(f.Entries)

	// First write
	var buf1 bytes.Buffer
	if _, err := f.WriteTo(&buf1); err != nil {
		t.Fatalf("first write failed: %v", err)
	}
	data1 := make([]byte, buf1.Len())
	copy(data1, buf1.Bytes())

	// Read back
	f2, err := ldcache.Read(bytes.NewReader(data1))
	if err != nil {
		t.Fatalf("failed to read back: %v", err)
	}

	if len(f2.Entries) != len(f.Entries) {
		t.Fatalf("entry count mismatch: got %d, want %d", len(f2.Entries), len(f.Entries))
	}

	// Verify entries match
	for i, e := range f.Entries {
		e2 := f2.Entries[i]
		if e.Key != e2.Key || e.Value != e2.Value || e.Flags != e2.Flags || e.OSVersion != e2.OSVersion || e.HWCap != e2.HWCap {
			t.Errorf("entry %d mismatch:\n  want: %s\n  got:  %s", i, e, e2)
		}
	}

	// Second write
	var buf2 bytes.Buffer
	if _, err := f2.WriteTo(&buf2); err != nil {
		t.Fatalf("second write failed: %v", err)
	}
	data2 := buf2.Bytes()

	// Binary comparison: write→read→write must produce identical output
	if !bytes.Equal(data1, data2) {
		t.Errorf("round-trip produced different output (%d vs %d bytes)", len(data1), len(data2))
		for i := 0; i < len(data1) && i < len(data2); i++ {
			if data1[i] != data2[i] {
				t.Errorf("first difference at byte %d: write1=0x%02x write2=0x%02x", i, data1[i], data2[i])
				break
			}
		}
	}
}

// TestStringSuffix verifies that the string-sharing optimization works correctly
// (keys that are suffixes of values share the string table entry).
func TestStringSuffix(t *testing.T) {
	f := ldcache.New()
	f.Entries = ldcache.EntryList{
		{Flags: 0x0303, Key: "libfoo.so.1", Value: "/usr/lib/libfoo.so.1"},         // key IS suffix
		{Flags: 0x0303, Key: "libspecial.so.1", Value: "/opt/custom/mylib.so.1.0"}, // key is NOT suffix
	}

	var buf bytes.Buffer
	if _, err := f.WriteTo(&buf); err != nil {
		t.Fatalf("write failed: %v", err)
	}

	// Read back and verify strings are correct
	f2, err := ldcache.Read(bytes.NewReader(buf.Bytes()))
	if err != nil {
		t.Fatalf("read failed: %v", err)
	}

	for i, e := range f.Entries {
		e2 := f2.Entries[i]
		if e.Key != e2.Key {
			t.Errorf("entry %d key mismatch: want %q, got %q", i, e.Key, e2.Key)
		}
		if e.Value != e2.Value {
			t.Errorf("entry %d value mismatch: want %q, got %q", i, e.Value, e2.Value)
		}
	}

	// The suffix-sharing entry ("/usr/lib/libfoo.so.1") should NOT have a
	// separate key string, so the output should be smaller than if both
	// key and value were stored separately.
	var bufNoShare bytes.Buffer
	f3 := ldcache.New()
	f3.Entries = ldcache.EntryList{
		{Flags: 0x0303, Key: "libfoo.so.1", Value: "/usr/lib/libfoo.so.1"},
	}
	f3.WriteTo(&bufNoShare)

	// With sharing: value + null = 21 bytes
	// Without sharing would be: key + null + value + null = 12 + 21 = 33 bytes
	// So shared should be smaller
	t.Logf("cache with suffix sharing: %d bytes", bufNoShare.Len())
}

// TestLdconfigReadOurs verifies that ldconfig can read cache files generated by our library.
func TestLdconfigReadOurs(t *testing.T) {
	ldconfigPath := findLdconfig()
	if ldconfigPath == "" {
		t.Skip("ldconfig not available")
	}

	f := ldcache.New()
	f.Entries = ldcache.EntryList{
		{Flags: 0x0303, Key: "libfoo.so.1", Value: "/usr/lib/libfoo.so.1.2.3"},
		{Flags: 0x0303, Key: "libbar.so.2", Value: "/usr/lib/libbar.so.2.0.0"},
	}
	sort.Sort(f.Entries)

	cacheFile := filepath.Join(t.TempDir(), "ld.so.cache")
	if err := f.SaveAs(cacheFile); err != nil {
		t.Fatalf("failed to write cache: %v", err)
	}

	out, err := exec.Command(ldconfigPath, "-C", cacheFile, "-p").CombinedOutput()
	if err != nil {
		t.Fatalf("ldconfig -p failed on our cache: %v\n%s", err, out)
	}

	output := string(out)
	for _, key := range []string{"libfoo.so.1", "libbar.so.2"} {
		if !strings.Contains(output, key) {
			t.Errorf("ldconfig -p output missing %q", key)
		}
	}
	t.Logf("ldconfig -p output:\n%s", output)
}

// TestLdconfigBinaryCompat creates shared libraries, runs ldconfig to generate an
// official cache, reads it with our library, and verifies:
//   - All expected entries are present
//   - Our sort produces the same order as ldconfig
//   - ldconfig can read files we generate
//   - Our round-trip output is binary-stable
func TestLdconfigBinaryCompat(t *testing.T) {
	if _, err := exec.LookPath("gcc"); err != nil {
		t.Skip("gcc not available")
	}
	ldconfigPath := findLdconfig()
	if ldconfigPath == "" {
		t.Skip("ldconfig not available")
	}

	tmpDir := t.TempDir()
	libDir := filepath.Join(tmpDir, "libs")
	if err := os.MkdirAll(libDir, 0755); err != nil {
		t.Fatal(err)
	}

	// Create test shared libraries with distinct sonames
	libs := []struct {
		file   string
		soname string
	}{
		{"libtstfoo.so.1.2.3", "libtstfoo.so.1"},
		{"libtstbar.so.2.0.0", "libtstbar.so.2"},
		{"libtstbaz.so.3.1.0", "libtstbaz.so.3"},
	}

	for _, lib := range libs {
		cmd := exec.Command("gcc", "-shared", "-o",
			filepath.Join(libDir, lib.file),
			"-Wl,-soname,"+lib.soname,
			"-xc", "-",
		)
		cmd.Stdin = strings.NewReader("void dummy(void) {}")
		if out, err := cmd.CombinedOutput(); err != nil {
			t.Skipf("failed to compile test library %s: %v\n%s", lib.file, err, out)
		}
	}

	// Run ldconfig with only our test directory to generate the official cache.
	cacheFile := filepath.Join(tmpDir, "ld.so.cache")
	confFile := filepath.Join(tmpDir, "empty.conf")
	if err := os.WriteFile(confFile, []byte(""), 0644); err != nil {
		t.Fatal(err)
	}

	cmd := exec.Command(ldconfigPath, "-f", confFile, "-C", cacheFile, libDir)
	if out, err := cmd.CombinedOutput(); err != nil {
		// Retry with sudo (some systems require root for ldconfig)
		cmd = exec.Command("sudo", ldconfigPath, "-f", confFile, "-C", cacheFile, libDir)
		if out2, err2 := cmd.CombinedOutput(); err2 != nil {
			t.Skipf("ldconfig failed:\n  without sudo: %v: %s\n  with sudo: %v: %s",
				err, out, err2, out2)
		}
	}

	// Read ldconfig's cache with our library
	f, err := ldcache.Open(cacheFile)
	if err != nil {
		t.Fatalf("failed to read ldconfig cache: %v", err)
	}

	if len(f.Entries) == 0 {
		t.Fatal("no entries found in ldconfig cache")
	}
	t.Logf("read %d entries from ldconfig cache", len(f.Entries))

	// Verify expected sonames are present
	foundSonames := make(map[string]bool)
	for _, e := range f.Entries {
		foundSonames[e.Key] = true
	}
	for _, lib := range libs {
		if !foundSonames[lib.soname] {
			t.Errorf("expected soname %q not found in cache entries", lib.soname)
		}
	}

	// Verify our sort produces the same order as ldconfig's
	originalKeys := make([]string, len(f.Entries))
	originalFlags := make([]ldcache.Flags, len(f.Entries))
	for i, e := range f.Entries {
		originalKeys[i] = e.Key
		originalFlags[i] = e.Flags
	}

	sort.Sort(f.Entries)

	for i, e := range f.Entries {
		if e.Key != originalKeys[i] || e.Flags != originalFlags[i] {
			t.Errorf("sort order differs from ldconfig at index %d:\n  ldconfig: %s (flags=%d)\n  ours:     %s (flags=%d)",
				i, originalKeys[i], originalFlags[i], e.Key, e.Flags)
		}
	}

	// Write with our library and verify round-trip stability
	ourCacheFile := filepath.Join(tmpDir, "our.ld.so.cache")
	if err := f.SaveAs(ourCacheFile); err != nil {
		t.Fatalf("failed to write cache: %v", err)
	}

	// Read our output back and write again - must be binary identical
	f2, err := ldcache.Open(ourCacheFile)
	if err != nil {
		t.Fatalf("failed to re-read our cache: %v", err)
	}

	ourCacheFile2 := filepath.Join(tmpDir, "our2.ld.so.cache")
	if err := f2.SaveAs(ourCacheFile2); err != nil {
		t.Fatalf("failed to re-write cache: %v", err)
	}

	data1, _ := os.ReadFile(ourCacheFile)
	data2, _ := os.ReadFile(ourCacheFile2)
	if !bytes.Equal(data1, data2) {
		t.Errorf("round-trip of ldconfig data not binary stable (%d vs %d bytes)", len(data1), len(data2))
		for i := 0; i < len(data1) && i < len(data2); i++ {
			if data1[i] != data2[i] {
				t.Errorf("first difference at byte %d: write1=0x%02x write2=0x%02x", i, data1[i], data2[i])
				break
			}
		}
	} else {
		t.Logf("round-trip binary stable (%d bytes)", len(data1))
	}

	// Verify ldconfig can read our output
	out, err := exec.Command(ldconfigPath, "-C", ourCacheFile, "-p").CombinedOutput()
	if err != nil {
		t.Errorf("ldconfig -p failed on our cache: %v\n%s", err, out)
	} else {
		output := string(out)
		for _, lib := range libs {
			if !strings.Contains(output, lib.soname) {
				t.Errorf("ldconfig -p output missing expected soname %q", lib.soname)
			}
		}
	}
}

func findLdconfig() string {
	for _, p := range []string{"ldconfig", "/sbin/ldconfig", "/usr/sbin/ldconfig"} {
		if abs, err := exec.LookPath(p); err == nil {
			return abs
		}
	}
	return ""
}
